# Generated by Django 4.2.6 on 2023-10-24 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_user_watch_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='watch_list',
            field=models.ManyToManyField(blank=True, related_name='itens', to='auctions.bid'),
        ),
    ]
